membership:
  kinds:
    - Premium
    - Plus
    - Reader

member:
  kinds:
    - Person
    - Family
    - Organization
  genders:
    - Male
    - Female
    - N/A
  age_groups:
    - Teen
    - Young
    - Middle
    - Senior
    - N/A

category:
  kinds:
    - Arts
    - Biographies
    - Business
    - Children
    - Comics
    - Computers
    - Cooking
    - Crafts
    - Engineering
    - Entertainment
    - Health
    - History
    - Humour
    - Law
    - Literature
    - Mathematics
    - Medicine
    - News
    - Others
    - Reference
    - Relationships
    - Religion
    - Politics
    - Science
    - Self-Help
    - Sports
    - Travel

creator:
  kinds:
    - Author
    - Artist
    - Publisher
    - Vendor

item:
  kinds:
    - Book
    - Periodical
    - Magazine
    - Newspaper
    - Compact Disc
    - DVD
  formats:
    - Paperback
    - Hardbound
    - Cased
  length_uoms:
    - Pages
    - Minutes
  languages:
    - Malayalam
    - English
    - Hindi
    - Tamil
    - Kannada
    - Arabic
    - Other
  rights:
    - Copyrighted
    - Copyright Expired
    - Patented
    - Authors Rights
    - Creative Commons
    - Orphan Works
    - Public Domain
  ratings:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

item_creator:
  roles:
    - Author
    - Actor
    - Director
    - Editor
    - Performer
    - Producer
    - Translator

copy:
  qualities:
    - {id: 'n', name: 'New'}
    - {id: 'u', name: 'Used'}
    - {id: 'w', name: 'Worn Out'}
    - {id: 'd', name: 'Damaged'}
  statuses:
    - {id: 'a', name: 'Available'}
    - {id: 'm', name: 'Misplaced'}
    - {id: 'l', name: 'Lost'}
    - {id: 'u', name: 'Unavailable'}

issue:
  defaults:
    period: 7

format:
  date: 'yyyy-mm-dd'
